[package]
name = "guarding"
version = "0.1.1"
authors = ["Inherd Group <group@inherd.org>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/inherd/guarding"
documentation = "https://github.com/inherd/guarding"
homepage = "https://github.com/inherd/guarding"
description = """
Guarding is a guardians for code, architecture, layered. Using git hooks and DSL for design guard rules.
"""
categories = ["text-processing", "command-line-interface", "development-tools"]
exclude = [
    ".github/*",
    ".gitattributes",
    ".adr.json",
]

[dependencies]
tree-sitter = "0.19.3"

# serialize
serde = { version = "1.0", features = ["derive"] }
serde_json     = "1"

[build-dependencies]
cc="*"
